build/build.cake
source/LottieToWinComp/LottieToWinCompTranslator.cs
source/WinCompData/CompositionContainerShape.cs
source/WinCompData/ContainerVisual.cs
source/WinCompData/IContainShapes.cs
source/WinCompData/ShapeVisual.cs
source/WinCompData/Tools/ListOfNeverNull.cs

ListOfNeverNull is an implementation detail so should not be public.
Always build the DLLs so that changes like these that can affect dependencies are checked during checkin.

Hide ListOfNeverNull from public view. Always build DLLs.

---

LottieGen/Program.cs
source/LottieData/Optimization/Optimizer.cs
source/LottieToWinComp/LottieToWinCompTranslator.cs

Take advantage of the ReadOnlySpan for key frame trimming.
Ensure that initial values are set for Position and Anchor if key frame trimming removes all the frames. This same work needs to be done for other animatable properties, so I've added the ability to know whether the initial value needs to be set, but the code isn't yet handling it everywhere.

Better key frame trimming. Definitely set initial transform value.

---

LottieGen/InstallLottieGenFromLocalBuild.cmd
LottieGen/Program.cs

Paths such as c:mystuff\foo.json were not being parsed correctly.
Also, fix the install script for LottieGen - I'd accidentally left a hard-coded version number in there.

Handle file patterns that have a drive letter and a relative path.

---

source/WinCompData/CodeGen/TreeReducer.cs

Add an optimization to remove shapes that have no brushes or transparent brushes. The shapes can't be seen, so let's not render them.

Remove transparent shapes

---

source/WinCompData/CompositionObject.cs
source/WinCompData/Tools/ObjectGraph.cs

On rare cases the codegen optimizer that replaces methods calls with field accesses would pull from a field before it had been initialized. This was caused by the code generator generating nodes in a different order from what the ObjectGraph visited them. I've updated the ObjectGraph to visit the nodes in the same order as the code generator.

Fixes NullReferenceException caused by codegen optimizer hole.

---

LottieGen/CommandLineOptions.cs
LottieGen/LottieFileProcessor.cs
LottieGen/Program.cs
source/Lottie/LottieVisualDiagnostics.cs
source/LottieData/LottieData.projitems
source/LottieData/Serialization/LottieCompositionXmlSerializer.cs
source/LottieData/Serialization/LottieCompositionYamlSerializer.cs
source/LottieData/Serialization/YamlMap.cs
source/LottieData/Serialization/YamlObject.cs
source/LottieData/Serialization/YamlObjectKind.cs
source/LottieData/Serialization/YamlScalar.cs
source/LottieData/Serialization/YamlSequence.cs
source/LottieData/Serialization/YamlWriter.cs

The YAML is easier to read than XML. The YAML output exists to help debug issues with Lottie files. It's much easier to read the YAML than the raw JSON. Note that the dump is not complete - some properties may not show up. It's at least as good as the XAML however so checking it in, and we can add more properties as needed.

Add ability to dump Lottie files as YAML.

---

.gitignore
source/WinCompData/Serialization/CompositionObjectXmlSerializer.cs
tests/CompareDirectories.cmd
tests/CompareDirectories.ps1
tests/LottieGenCorpus.cmd
tests/LottieGenCorpus.ps1

LottieGenCorpus will create a directory with the output from running LottieGen over a corpus of Lottie files. The output can then be compared with a baseline run to detect regressions.
Add scripts to allow comparing the outputs of different versions of LottieGen

Adding LottieGenCorpus for generating output for testing.

---

LottieGen/LottieFileProcessor.cs
LottieGen/Program.cs
dlls/LottieToWinComp/LottieToWinComp.dll.csproj
source/LottieToWinComp/LottieToWinCompTranslator.cs
source/WinCompData/CodeGen/CSharpInstantiatorGenerator.cs
source/WinCompData/CodeGen/InstantiatorGeneratorBase.cs
tests/CompareDirectories.ps1

Use of Win2D geometry groups to group paths that are part of the same shape group. Previously we just drew the paths on top of each other, but that's not correct when the paths overlap. The typical case is concentric shapes where the space between them is used like a stroke.
There are many potential cases that we don't yet handle with this change, e.g. we don't handle animation of the shapes, or other shapes, but the concentric non-animated shapes as a stroke is common enough to be worth doing alone.

Handle some cases of shape groups that contain multiple paths.

---

source/LottieToWinComp/LottieToWinCompTranslator.cs
source/LottieToWinComp/TranslationIssues.cs

If there are multiple shapes in a group or layer, in many cases we may not be combining them correctly. Report the cases we know that we have trouble with.
Also removed some allocations that can now be avoided due to our use of Span in the Repeater code.

Detect and report cases where we can't combine shapes correctly.

---

LottieGen/LottieFileProcessor.cs
LottieGen/Program.cs
source/Lottie/LottieVisualDiagnostics.cs
source/LottieData/LottieData.projitems
source/LottieData/Path.cs
source/LottieData/Serialization/LottieCompositionXmlSerializer.cs
source/LottieData/Serialization/LottieCompositionYamlSerializer.cs
source/LottieReader/Serialization/LottieCompositionReader.cs
source/LottieToWinComp/LottieToWinCompTranslator.cs

It was called Shape originally because its type code is "sh" and it is contained by a ShapeLayer, but it's not the right name. Path is the right name.

Rename the Lottie Shape class to Path.

---

LottieGen/LottieFileProcessor.cs
source/LottieReader/Serialization/LottieCompositionReader.cs
tests/LottieGenCorpus.ps1

I came across a Lottie with an empty color string, so rather than failing, treat that as transparent.
Improved the way the LottieGenCorpus discovers errors by making it watch stderr as well as stdout.

Allow color strings to be empty in Lottie json files.

---

LottieGen/Glob.cs

Fix SplitPath to always return directory path with a trailing slash to make it easier for callers to deal with the path.

Globbing was broken for some types of path. 

---

LottieViewer/App.xaml.cs

Achieves parity with store app by:
- setting Lottie's Stretch to Uniform
- removing fade-out storyboard (would like to add this back in after I've figured out how to use group opacity instead of push-down opacity in xaml)

Update LottieViewer splashscreen

---

LottieViewer/App.xaml.cs

Updated splashGrid to a border so that it can have only one child, the player.  This mitigates any re-parenting issues for original window content that our previous approach may have caused.

Fix Splashscreen Reparenting bug

---

Lottie-Windows/Lottie-Windows.csproj
LottieGen/LottieGen.csproj
LottieViewer/LottieViewer.csproj
dlls/LottieData/LottieData.dll.csproj
samples/LottieSamples/LottieSamples.csproj
samples/LottieSamples/Scenarios/JsonPage.xaml

Updating versions and fixing a typo in the LottieSamples app.
This change is mainly about getting the LottieSamples app onto the official Lottie-Windows package, but updating other packages while we're here, and fixing a typo in the LottieSamples app.

Updating versions of various packages.

---

source/LottieToWinComp/LottieToWinCompTranslator.cs

Previously we were clipping precomps to the size of their parents, which was never right.

Clip precomps with the correct size.

---

source/UIData/CodeGen/CxInstantiatorGenerator.cs

Previously we were always instantiating these from code-behind so the visiblity didn't matter. XAML markup use requires that they are public.

Make the generated CX classes public. This allows them to be used in XAML

---

source/LottieToWinComp/LottieToWinCompTranslator.cs

There was a comment about a bug where we had to add an intermediate ContainerVisual in CompositeVisuals. It turns out this is not a bug and just something we need to do. This change updates the comment.

Updated comment on CompositeVisuals

---

source/Lottie/Instantiator.cs
source/LottieToWinComp/LottieToWinCompTranslator.cs
source/UIData/CodeGen/InstantiatorGeneratorBase.cs
source/UIData/CodeGen/Optimizer.cs
source/WinCompData/ColorKeyFrameAnimation.cs
source/WinCompData/CompositionColorSpace.cs
source/WinCompData/WinCompData.projitems

After Effects (and the web) use RGB interpolation for color animations. Composition support HSL and RGB, but defaults to HSL. HSL is rarely useful if the animation goes through white or black because there are multiple representations of white and black so the interpolation is poorly specified.
With this change, Lottie-Windows always uses RGB interpolation.

Override the default interpolation color space of ColorKeyFrameAnimation to align with After Effects

---

source/LottieToWinComp/LottieToWinCompTranslator.cs

Until now we couldn't turn on the VisualSurface code because VisualSurface was not in the SDK we were using.

Enable VisualSurface now that we are using the 1903 SDK.

---

LottieGen/CommandLineOptions.cs
LottieGen/DataTable.cs
LottieGen/LottieFileProcessor.cs
LottieGen/Profiler.cs
LottieGen/Program.cs
LottieGen/Reporter.cs
source/LottieData/Tools/Stats.cs
source/LottieToWinComp/LottieToWinCompTranslator.cs
source/LottieToWinComp/TrimmedAnimatable.cs

I'm doing this to get ready for testing gradients.
Previously we had an awkward CSV output and a verbose option for LottieGen. Now we have a general DataTable that allows any data to be written to a TSV file.
Fixed some edge-case bugs I found in translation around gradients during testing.

Better stats for LottieGen

---

LottieGen/CommandLineOptions.cs
LottieGen/LottieFileProcessor.cs
LottieGen/Program.cs
source/WinUIXamlMediaData/LoadedImageSurfaceFromStream.cs

The -ClassName option allowed you to override the name generated for a class for a Lottie. However it was rarely used, and it makes no sense when using globs to specify more than one Lottie file. The functionality to control your class name is still available via a workaround: rename your .json file.

Remove class name option

---

Lottie-Windows.sln
LottieGen/CommandLineOptions.cs
LottieGen/LottieFileProcessor.cs
LottieGen/Program.cs
source/Issues/LT0034.md
source/Lottie/LottieVisualDiagnostics.cs
source/Lottie/LottieVisualSource.cs
source/LottieReader/Serialization/LottieCompositionReader.cs
source/LottieToWinComp/CompositionObjectFactory.cs
source/LottieToWinComp/LottieToWinComp.projitems
source/LottieToWinComp/LottieToWinCompTranslator.cs
source/LottieToWinComp/TranslationIssues.cs
source/LottieToWinComp/TranslationResult.cs
source/UIData/CodeGen/InstantiatorGeneratorBase.cs
source/UIData/Tools/ApiCompatibility.cs
source/WinCompData/MetaData/UapVersionAttribute.cs

This adds a number of pieces required to generate version-adaptive code, but doesn't
yet hook those pieces up. This allows testing against a corpus to ensure nothing is
broken. A future commit will add version-adaptivity.

Prerequisites for versioning.

---

source/UIData/CodeGen/InstantiatorGeneratorBase.cs

#161: This issue was producing uncompilable code on some very simpler Lottie files that didn't need references to the root node except through the IAnimatedVisual interface.

Fix for #161: Ensure storage is allocated for the root node in codegen.

---

source/UIData/CodeGen/CxInstantiatorGenerator.cs

Fix incorrect class name in constructor calls in CX codegen.
Fix issue #160 - use of Microsoft::WRL namespace was not synced with include of <wrl.h>

CX codegen fixes

---

source/Lottie/Instantiator.cs
source/LottieToWinComp/LottieToWinCompTranslator.cs
source/UIData/CodeGen/InstantiatorGeneratorBase.cs
source/UIData/CodeGen/Optimizer.cs
source/UIData/CodeGen/Stringifier.cs
source/WinCompData/CompositionBorderMode.cs
source/WinCompData/Serialization/CompositionObjectXmlSerializer.cs
source/WinCompData/Visual.cs
source/WinCompData/WinCompData.projitems

The default BorderMode for Visuals is Inherit, and if not specified the value Hard (i.e. not anti-aliased) is passed into the root.
The default worked for us previously because the desktop tree sets the BorderMode to Soft and we inherit it so we got Soft behavior everywhere.
However the trees created for masks and mattes are not rooted in the desktop, so they were getting set to Hard and some edges looked aliased.
This change adds the ability to set the BorderMode and sets it to Soft for the trees created for masks and mattes.

Anti-alias the edges of masks and mattes for a smoother result.

---

source/UIData/CodeGen/NodeNamer.cs

C++ gets confused if you try to "new" a type with the same name as something else in scope. This was causing compilation failures on generated code when we tried to new a CompositionPath and there was a method called CompositionPath().
This only affected C++ because C# doesn't expect a "new" of anything but a type.
The workaround is to always use counter-suffixed names for node names (and therefore for method names).
Previously we special-cased nodes for which there was only one with a particular type. This change removes that special-casing.

Ensure node names don't conflict with type names for C++.

---

source/LottieToWinComp/LottieToWinCompTranslator.cs

We were correctly recognizing that we couldn't compose strokes of different kinds, but then we tried to compose them anyway which would result in a failed cast.

Fix bug where combining of strokes could fail during translation.

---

source/LottieToWinComp/Float32.cs
source/LottieToWinComp/LottieToWinCompTranslator.cs

Windows.UI.Composition key frames need to have distinct progress values. Sometimes during translation we need to place a key frame as close as possible to a previous key frame. Before this change we did that by adding a small constant however that doesn't always give the smallest possible increment (because the increment depends on the exponent of the float, and because the constant we chose was conservative). With this change we actually calculate the next float value, so it is guaranteed to be as close as possible to the previous key frame.

Use the most precise version of "next float".

---

LottieGen/README.md

6.0.0 is out, and 6.1.0 is what we're working on, so the docs should refer to them.
I also added directions for running lottiegen without installing.

Update the LottieGen readme to refer to 6.0.0 and 6.1.0

---

source/UIData/CodeGen/CxInstantiatorGenerator.cs

std::vector returns a size_t from size(). We assign it to a UINT which results in a warning. Adding a cast to make that warning go away.

Add a cast to eliminate a compiler warning.

---

source/LottieToWinComp/CompositionObjectFactory.cs
source/LottieToWinComp/LottieToWinCompTranslator.cs

Now that we have version-dependent translation, we can replace the workaround for CompositionRectangleGeometry (which misbehaves in RS5) with version-dependent behavior. If on v8 or beyond, we will use CompositionRectangleGeometry instead of CompositionRoundedRectangleGeometry with tiny corners.

Remove workaround for CompositionRectangleGeometry when running on UAP v8.

---

source/LottieToWinComp/LottieToWinCompTranslator.cs
source/UIData/CodeGen/InstantiatorGeneratorBase.cs
source/UIData/Serialization/CompositionObjectDgmlSerializer.cs
source/WinCompData/CompositionAnimation.cs
source/WinCompData/CompositionObject.cs

This adds a facility for arbitrary metadata to be added to CompositionObject and uses it for the IDescribable interface.
The metadata facility is being added so that we can smuggle information from names in LottieData through to the optimizer and code generator.
I also made the IDescribable implementation on CompositionObject explicitly implemented so that it doesn't pollute the API surface of CompositionObject. The goal is to have only one extra concept in WinCompData, i.e. classes look just like the real WinComp classes, except with one addition: metadata. IDescribable + metadata would have been 2 concepts.
And the IDescribable storage is now implemented by the metadata store, which should result in space savings at runtime as we now reserve only one pointer (for the metadata) rather …

Adding a metadata facility to CompositionObject.

---

LottieViewer/MainPage.xaml
LottieViewer/MainPage.xaml.cs

LottieGen has a lot of options for code gen. LottieViewer doesn't have a good way to make those options available. So rather than making LottieViewer more complicated, I'm removing the codegen functionality completely. When you need to codegen, use LottieGen - it's waaaaaay better.

Remove codegen functionality from LottieViewer.

---

LottieGen/LottieFileProcessor.cs
LottieViewer/MainPage.xaml.cs
dlls/UIData/UIData.dll.csproj
source/Lottie/LottieVisualDiagnostics.cs
source/Lottie/LottieVisualSource.cs
source/UIData/CodeGen/CSharpInstantiatorGenerator.cs
source/UIData/CodeGen/CxInstantiatorGenerator.cs
source/UIData/CodeGen/InstantiatorGeneratorBase.cs
source/UIData/CodeGen/Stringifier.cs

Add ability to convert GenericData object to code-genned Windows.Data.Json objects.
This change passes the data through but doesn't yet change the output of the code generators. That will come soon when we figure out what clients would like to have (e.g. should it be JSON, or some specialized properties).

Pass Lottie metadata (frame rate, etc) through translator to the code generators.

---

source/LottieToWinComp/LottieToWinComp.projitems
source/LottieToWinComp/LottieToWinCompTranslator.cs
source/LottieToWinComp/PropertyBindingsParser.cs

The parser is designed to allow designers to embed information about how colors should be hooked up to theme colors in the app or OS on which the Lottie runs.
Currently the parser is hooked up to parse property bindings from solid color fills, but it doesn't do anything with the result - this is just to get some coverage on it.
Eventually the property bindings will results in generated code that puts the given color in a CompositionPropertySet property and binds it appropriately so that clients can change the color at runtime.

Adding a property bindings language parser.

---

LottieGen/LottieFileProcessor.cs
source/Lottie/Instantiator.cs
source/Lottie/LottieVisualSource.cs
source/LottieToWinComp/LottieToMultiVersionWinCompTranslator.cs
source/LottieToWinComp/LottieToWinCompTranslator.cs
source/UIData/Tools/Optimizer.cs
source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs
source/WinCompData/CompositionGetValueStatus.cs
source/WinCompData/CompositionPropertySet.cs
source/WinCompData/Serialization/CompositionObjectXmlSerializer.cs
source/WinCompData/WinCompData.projitems

Add support for Color values in CompositionPropertySet.
Add support for TryGet* methods in CompositionPropertySet.
Refactor the CompositionPropertySet implementation so that it's easier to add new types.
Adds a switch to the translator to determine whether or not it recognizes property bindings. Property bindings are only useful for codegen so this switch is off for LottieVisualSource and on for LottieGen.
Translator will now insert a property for a solid color fill that has a property binding for "Color".

More support for property bindings.

---

tests/LottieGenCorpus.ps1

This makes it easier to know whether you are running tests with the expected version of LottieGen.dll.

Show the timestamp from LottieGen.dll in LottieGenCorpus

---

source/LottieToWinComp/ExpressionFactory.cs
source/LottieToWinComp/LottieToWinCompTranslator.cs
source/UIData/Tools/Optimizer.cs
source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs
source/UIDataCodeGen/CodeGen/NodeNamer.cs
source/WinCompData/CompositionObject.cs
source/WinCompData/CompositionPath.cs
source/WinCompData/CompositionPropertySet.cs
source/WinCompData/Expressions/ColorRGB.cs
source/WinCompData/Expressions/Expression.cs
source/WinCompData/Expressions/LessThan.cs
source/WinCompData/Expressions/Max.cs
source/WinCompData/Expressions/Min.cs
source/WinCompData/Expressions/ScalarSubchannel.cs
source/WinCompData/Expressions/Vector2.cs
source/WinCompData/Expressions/Vector3.cs
source/WinCompData/Expressions/Vector4.cs
source/WinCompData/IDescribable.cs
source/WinCompData/Mgcg/CanvasGeometry.cs
source/WinCompData/Serialization/CompositionObjectXmlSerializer.cs
source/WinCompData/WinCompData.projitems
source/WinUIXamlMediaData/LoadedImageSurface.cs

Add support for Vector3 and Vector4 in CompositionPropertySet.
Fix bug in CompositionPropertySet.TryGet* logic.
Add IDescribable.Name so that brushes that are bound to property set values can have names that match the property set name.
Add support for scalar subchannel accessors in animation expressions.
Add support for ColorRGB constructor in animation expressions.
Add support for Vector4 in animation expressions.

Enable binding of SolidColorFill to property set values.

---

source/UIDataCodeGen/CodeGen/NodeNamer.cs

In all cases except "CompositionPath" the factory names in the generated code do not have the "Composition" prefix. This is because "Composition" doesn't add anything useful to the meaning, so it's just noise. But we never did that for CompositionPath. Now we do.

More consistent naming for factories.

---

source/WinCompData/Expressions/Expression.cs
source/WinCompData/Expressions/ScalarSubchannel.cs
source/WinCompData/Expressions/Vector2.cs
source/WinCompData/Expressions/Vector3.cs
source/WinCompData/Expressions/Vector4.cs

This includes some cleanup to make Vector expression code more consistent, and takes advantage of C# 7 switching on types.

Vector4 didn't support simplification. Now it does.

---

LottieGen/LottieGen.csproj
LottieGen/README.md
source/UIDataCodeGen/CodeGen/NodeNamer.cs

This is a follow-up from a previous PR where there were some questions about the NodeNamer, so I've refactored it to take advantage of C# switch expressions and added better comments.
Also move LottieGen to .NET Core 3.1 (was 2.2). This means we can use newer features, and we get an actual exe rather than having to use the "dotnet" bootstrapper.

Improve NodeNamer readability.

---

source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs

CompositionPath factories get inlined during codegen unless they're shared. Because we were naming the factory nodes before determining whether the CompostionPath factories could be inlined, we ended up generating names for CompositionPaths that would never get a name. The result was that there would be gaps in the number of CompostionPath factories (e.g. CompostionPath_0, CompostionPath_4). With this change the CompostionPath numbers will be contiguous because we do the inlining before the naming.

Make CompositionPath names start at 0.

---

source/WinCompData/Expressions/Expression.cs
source/WinCompData/Expressions/ExpressionType.cs
source/WinCompData/Expressions/Expression_.cs

This is needed for an unpcoming change which uses KeyFrame<Expressions.Color>. KeyFrame<T> requires that T is IEquatable (to support animation trimming).
Expressions are considered equivalent if their simplified text is exactly the same. It does not guarantee that the expression evaluates to the same value, but it does guarantee that if the expressions claim to be equal, they will evaluate to the same value.

Make expressions equatable.

---

source/LottieData/Color.cs
source/LottieData/ExtensionMethods.cs
source/LottieData/LinearGradientFill.cs
source/LottieData/LinearGradientStroke.cs
source/LottieData/LottieData.projitems
source/LottieData/Mask.cs
source/LottieData/Opacity.cs
source/LottieData/OpacityGradientStop.cs
source/LottieData/Optimization/GradientStopOptimizer.cs
source/LottieData/RadialGradientFill.cs
source/LottieData/RadialGradientStroke.cs
source/LottieData/RepeaterTransform.cs
source/LottieData/Serialization/LottieCompositionXmlSerializer.cs
source/LottieData/Serialization/LottieCompositionYamlSerializer.cs
source/LottieData/ShapeFill.cs
source/LottieData/ShapeStroke.cs
source/LottieData/SolidColorFill.cs
source/LottieData/SolidColorStroke.cs
source/LottieData/Transform.cs
source/LottieReader/Serialization/LottieCompositionReader.cs
source/LottieToWinComp/LottieToWinCompTranslator.cs

Opacity is special because it's expressed in Lottie as a percent, which is inconvenient for multiplication with alpha.
Giving an Opacity a strong type allows us to abstract the percent details, and also make the translator clearer because it's obvious where a value is being used for opacity.

Strong type of Lottie Opacity.

---

source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs

This saves a line of code per object, and it avoids an unnecessary call at runtime.

Codegen: pass parameters to the Compositor.Create* methods where possible

---

source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs

Avoid creating factories for CubicBezierEasingFunctions that are not shared.
This makes the code smaller and a bit easier to read.

Inline the creation of CubicBezierEasingFunctions.

---

source/LottieData/LottieData.projitems
source/LottieData/Opacity.cs
source/LottieData/RepeaterTransform.cs
source/LottieData/Rotation.cs
source/LottieData/Serialization/LottieCompositionXmlSerializer.cs
source/LottieData/Serialization/LottieCompositionYamlSerializer.cs
source/LottieData/Transform.cs
source/LottieData/TrimPath.cs
source/LottieReader/Serialization/LottieCompositionReader.cs
source/LottieToWinComp/LottieToWinCompTranslator.cs

Previously we just used a double and you had to know that it was represented in degrees. Now the type directly represents 2d rotation and has properties to express the rotation in degrees and in radians.
This change also fixed up a few places I noticed where the Opacity type was still talking about OpacityPercent.

Add a type to represent rotation.

---

source/LottieToWinComp/LottieToWinCompTranslator.cs

Previously we always set property-bound colors to red to make them visible. With this change we are a little smarter about it: we show the color the designer used, and if that color was animated we find a high-alpha color amongst the keyframes the designer used.

Set a smart default value for property-bound colors.

---

source/LottieData/Serialization/LottieCompositionYamlSerializer.cs

Some of the Yaml field names were wrong. This change gets rid of the hand-written strings and replaces them with nameof(...) so that the names stay in sync with LottieData.
And did some small cleanup and refactoring while I was there.
This does change the Yaml output from what it was - that is intentional.

Use nameof to keep Yaml field names in sync with Lottie data property names

---

source/Lottie/Instantiator.cs
source/UIData/Tools/Canonicalizer.cs
source/UIData/Tools/Optimizer.cs
source/UIData/Tools/Stats.cs
source/UIData/Tools/TreeReducer.cs
source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs
source/WinCompData/CompositionPropertySet.cs
source/WinCompData/MetaData/PropertySetValueType.cs
source/WinCompData/Serialization/CompositionObjectXmlSerializer.cs
source/WinCompData/WinCompData.projitems

This also gets rid of the CompositionPropertySet.IsEmpty property in order to reduce the number of non-standard (i.e. not in Windows.UI.Composition) apis on the class.
This change is in preparation for some new features coming to property binding.

Add ability to get the type for a given CompositionPropertySet property name.

---

source/LottieToWinComp/LottieToWinCompTranslator.cs
source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs
source/UIDataCodeGen/CodeGen/NodeNamer.cs
source/WinCompData/CompositionAnimation.cs

Previously we special-cased the naming of the root node and the root progress animations during codegen, but did some other special naming during translation. With this change we do all of the special naming at codegen time.
This change also includes better handling of name collisions in the node namer. If 2 or more nodes get the same name, we have to append a counter value to the name to differentiate them. Previously we appended a counter even if there was only 1 node, in order to prevent C++ from getting confused when a method name was the same as a type name. Now we keep track of whether a name is also a type name, and can therefore avoid appending the counter more often. This makes for much nicer naming (i.e. they don't have a _0 suffix) for most singleton objects.

Simplify node naming.

---

Lottie-Windows/Lottie-Windows.csproj

Changes have been made to the Lottie Windows csproj to include additional metadata for the generated NuGet package including a description (taken from the [README](https://github.com/windows-toolkit/Lottie-Windows/tree/master/Lottie-Windows)) and package tags.
This change is related to #253

Added Lottie-Windows package description and tags

---

.github/CODEOWNERS

This is a better way to manage responsibilities.

Remove individual code owners and replace with the Lottie group.

---

README.md
samples/LottieSamples/Scenarios/JsonPage.xaml
samples/LottieSamples/Scenarios/ModifyPage.xaml
samples/LottieSamples/Scenarios/SegmentPage.xaml
source/LottieData/Optimization/GradientStopOptimizer.cs

At one point we were in a habit of calling it "AfterEffects", which is wrong.

Fixing spacing in all mentions of "After Effects".

---

source/Issues/LT0027.md
source/Issues/LT0036.md
source/LottieData/Path.cs
source/LottieToWinComp/LottieToWinCompTranslator.cs
source/LottieToWinComp/TranslationContext.cs
source/LottieToWinComp/TranslationIssues.cs

This change will allow some (not very common) cases of grouped animated paths where the animation can be optimized away.
In the cases it can't handle, it now raises an issue to make it clear that there is a problem.

Improve handling of grouped animated paths.

---

source/LottieData/BezierSegment.cs
source/LottieData/LottieData.projitems
source/LottieData/Mask.cs
source/LottieData/Optimization/Optimizer.cs
source/LottieData/Path.cs
source/LottieData/PathGeometry.cs
source/LottieData/Serialization/LottieCompositionXmlSerializer.cs
source/LottieData/Serialization/LottieCompositionYamlSerializer.cs
source/LottieReader/Serialization/Animatables.cs
source/LottieReader/Serialization/LottieCompositionReader.cs
source/LottieToWinComp/CanvasGeometryCombiner.cs
source/LottieToWinComp/CubicBezierFunction2.cs
source/LottieToWinComp/LottieToWinCompTranslator.cs
source/LottieToWinComp/ProgressMapFactory.cs
source/LottieToWinComp/TranslationContext.cs

In most cases, a closed path is simply one that ends where it starts, so we just left all our paths open and relied on After Effects to complete the path.
But that was wrong in some cases - specifically the closing of the path determines whether a miter or an end cap is used where the end meets the start.

We were ignoring the "closed" property on paths.

---

source/LottieData/PathGeometry.cs
source/UIDataCodeGen/CodeGen/NodeNamer.cs

Also, fixing a bug in the NodeNamer that caused it to add leading 0's to object counters unnecessarily when there were exactly 10/100/1000/etc objects.

PathGeometry didn't implement GetHashCode so it wasn't being canonicalized.

---

source/LottieData/KeyFrame.cs
source/LottieToWinComp/LottieToWinComp.projitems
source/LottieToWinComp/LottieToWinCompTranslator.cs
source/LottieToWinComp/PathGeometryGroup.cs

This will allow animated path groups in most cases. It won't allow cases where paths in the group are animated at different rates (i.e. they have different keyframes or easings), but those appear to be rare.

Handle animated path groups in most cases.

---

source/LottieData/DrawingDirection.cs
source/LottieData/Ellipse.cs
source/LottieData/LottieData.projitems
source/LottieData/Path.cs
source/LottieData/Polystar.cs
source/LottieData/Rectangle.cs
source/LottieData/Serialization/LottieCompositionYamlSerializer.cs
source/LottieData/Shape.cs
source/LottieReader/Serialization/Enums.cs
source/LottieReader/Serialization/LottieCompositionReader.cs
source/LottieReader/Serialization/ShapeLayerContents.cs
source/YamlData/YamlScalar.cs

Drawing direction determines where the path of the shape starts and ends. This matters when trimming the path. I think that if the shape is closed (e.g. an ellipse) and the drawing is in reverse
then the trim start and trim end get swapped. Still trying to figure out all the details.
There will be at least one more change to support drawing direction. This is just to get the
bones of the parsing in place. Following changes will use it during translation.
Note that the enum values don't have descriptive names because I'm not sure what they should be yet.

Support reading of drawing direction.

---

LottieGen/LottieFileProcessor.cs
LottieGen/Reporter.cs

The recent output coloring made the problem obvious - when we run Lottiegen over multiple files there are numerous threads that are writing to the console and can interleave their writes.
With this change, the writes that need to be kept together have a way of being kept together.

Make writes to the console transactional where necessary.

---

source/LottieData/Polystar.cs
source/LottieData/Rectangle.cs
source/LottieData/RoundedCorner.cs
source/LottieData/Serialization/LottieCompositionXmlSerializer.cs
source/LottieData/Serialization/LottieCompositionYamlSerializer.cs
source/LottieReader/Serialization/ShapeLayerContents.cs
source/LottieToWinComp/ExpressionFactory.cs
source/LottieToWinComp/LottieToWinCompTranslator.cs
source/WinCompData/CompositionObject.cs

Composition and After Effects use different models for expression rounded rectangles. Composition has a Vector2 CornerRadius that can be set to anything. As the radius trends towards half the size the rectangle looks more like an ellipse, but when the CornerRadius gets bigger than half the size it starts looking like a weird 4-sided star thing. After Effects uses a scalar Roundness value and always caps the value so that you can't go beyond a circle.
Previously we were not accounting for this difference in models.
This is not a complete fix, but it fixes a lot of egregious cases. It's not complete because there is another After Effects concept called "Rounded corners" which interacts with rounded rectangles in a complex fashion, and we don't yet support that correctly. It seems to be …

Handle rounded rectangles more accurately

---

source/LottieToWinComp/LottieToWinCompTranslator.cs
source/LottieToWinComp/PathGeometryGroup.cs
source/LottieToWinComp/TranslationContext.cs
source/WinCompData/KeyFrameAnimation.cs

I found a Lottie file that during translation would generate 2 keyframes at the same progress. That's illegal for Composition.
The Lottie file that triggered this had one path in a geometry group at frame 48 and another in the same group at 48.000000357.
This issue is caused by the fact that we convert unique key frame numbers as doubles to progress values as floats. Floats have less resolution, so if 2 keyframes were really close together then they might end up with identical progress values.
It's also an issue when we group animated paths because the 2 paths might have key frame numbers that are slightly different but end up at the same progress value. As long as we prevent identical progress values that's fine, but if we can be a bit smarter about how we compare frame numbers during …

Prevent duplicated keyframe progress

---

source/LottieReader/Serialization/LottieCompositionReader.cs

Previously we would complain that this field is unexpected. It's an object added by the LottieFiles.com [plugin](https://lottiefiles.com/plugins/after-effects)/ We don't do anything interesting with it yet, but at least we shouldn't frighten the user with a warning.

Ignore the "meta" field in Lottie files.

---

source/UIDataCodeGen/CodeGen/NodeNamer.cs

This is to make it easier to see from the factory method for a gradient where the gradient stops lie.
I'm adding this because I started investigating why gradient stops are sometimes different from run to run of LottieGen and realized that this change would make reading the generated code easier to help figure out what's going on.

Include the offset in the name of a gradient stop.

---

source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs

This would cause a compile failure of the generated code because the constant was referenced but never found.

Fix: LottieGen was not creating constants for scalar theme properties.

---

source/Lottie/Instantiator.cs
source/LottieToWinComp/CompositionObjectFactory.cs
source/LottieToWinComp/LottieToWinCompTranslator.cs
source/UIDataCodeGen/CodeGen/NodeNamer.cs
source/WinCompData/CompositionRectangleGeometry.cs
source/WinCompData/CompositionRoundedRectangleGeometry.cs

CompositionRectangleGeoemetry doesn't anti-alias correctly. Rounded rectangles with tiny corner radiuses work fine, so use them instead.
Rectangles are expected to be fixed eventually, and when they are we can take advantage of their better (than rounded) perf, but until then they aren't reliable.

Stop using CompositionRectangleGeometry

---

source/LottieReader/Serialization/ShapeLayerContents.cs

It's a mystery as to what this field does. It appears to be related to miter limit, but that's already handled by "ml". Some tool is adding it, although BodyMovin importer doesn't seem to know what it is.

Ignore the "ml2" field in Lottie files.

---

LottieGen/CommandLineOptions.cs
LottieGen/CommandLineTokenizer.cs
LottieGen/LottieFileProcessor.cs
LottieGen/Program.cs
source/Lottie/LottieVisualSource.cs
source/LottieToWinComp/LottieToMultiVersionWinCompTranslator.cs
source/LottieToWinComp/LottieToWinComp.projitems
source/LottieToWinComp/LottieToWinCompTranslator.cs
source/LottieToWinComp/TranslationContext.cs
source/LottieToWinComp/TranslationOptions.cs
source/LottieToWinComp/TranslatorConfiguration.cs
source/WinCompData/Wui/Color.cs

When enabled with -GenerateColorBindings, LottieGen will create bindings
for each non-animated color it finds in a fill or stroke. This will
allow the colors to be changed at runtime.
This is particularly handy for animations that have a single color such
as those found at https://www.lottieflow.com.
The feature is less flexible than theme property bindings because:
a) it only supports colors
b) it doesn't give the designer much control over which parts of the
animation are bindable.
c) it doesn't allow the designer to choose the names used for the
bindings.
The binding name is based on the color, so a black color will generate a property
called "ColorBlack".
For single-color Lottie files we could be clever and name the property
"Foreground". I'm not doing that right now because we don't …

Add ability to automatically bind to the colors in a Lottie's palette.

---

LottieViewer/FeedbackLottie.xaml
LottieViewer/MainPage.xaml
LottieViewer/Scrubber.xaml
LottieViewer/Stage.xaml

This PR adds UIA names and improves the accessibility of the Lottie Viewer app. Screenshot of Accessibility Insights before and after this PR:
Before:
After:
Now, this closes #52

Improve accessibility of lottie viewer

---

LottieGen/LottieFileProcessor.cs
source/LottieData/Optimization/Optimizer.cs
source/LottieData/Vector2.cs
source/LottieToWinComp/AnimatableVector3Rewriter.cs
source/LottieToWinComp/AnimatableVector3ToAnimatableXYZ.cs
source/LottieToWinComp/LottieToWinComp.projitems
source/LottieToWinComp/LottieToWinCompTranslator.cs
source/LottieToWinComp/TranslationContext.cs

Lottie allows Vector2/Vector3 to have different easings for each channel. When that happens we cannot translate
them as Vector2/Vector3 animations, because WinComp only supports an easing for the whole Vector2/Vector3.
Now we will recognize this case and first translate to the AnimatableVector3 to an AnimatableVectorXYZ and
create separate animations for each channel.
This change only supports separate easings in that cases that we've seen in the corpus. Complete support is
a lot more expensive code (i.e. expensive to maintain because it requires a lot of repeating of the same
patterns over and over with slight changes).
Current support includes:
* Size of a shape
* Size of a rectangle
* Radius of an ellipse
* Position of a shape

Support animated vector2/vector3 with easings that differ between channels

---

source/UIDataCodeGen/CodeGen/NodeNamer.cs

Very rarely the generated code contained name collisions as a result of a name having the same form as a name with a counter suffix, e.g. Rectangle_15 looks like a name with a counter suffix but it might just be a 15x15 rectangle.
We now check for collisions when adding a counter suffix.

Fix rare case name collision in generated code.

---

source/LottieData/Optimization/Optimizer.cs
source/LottieData/Sequence.cs
source/LottieData/Serialization/LottieCompositionYamlSerializer.cs
source/LottieReader/Serialization/Animatables.cs
source/LottieReader/Serialization/LottieCompositionReader.cs
source/LottieToWinComp/LottieToWinCompTranslator.cs

This has been bugging me for ages. It was an attempt to switch the code over to using Span, but in the end it didn't make thing better, and required extra indirections to get at the items in the sequence.
While I'm here I'm adding some other nice touches, including avoiding copying of arrays when create a sequence, and allowing the creation of a sequence from a single item.

Eliminate the ReadOnlySpan from Sequence.

---

source/UIData/Tools/GraphCompactor.cs
source/UIData/Tools/Properties.cs
source/WinCompData/KeyFrameAnimation.cs

This problem has always existed but it didn't matter until we started using subchanel animations for Scale (Scale.X and Scale.Y) in order to support multiple easings.
The issue was that we ask which properties have non-default values by looking at whether the property is set, and whether there is an animation for that property.
But when we find animations for a property we need to ignore the subchannel part of the name (the ".X" part).

Recognize animation subchannels when discovering non-default properties.

---

source/LottieData/ExtensionMethods.cs
source/LottieToWinComp/LottieToWinCompTranslator.cs
source/WinCompData/Wui/Color.cs

When LottieGen generates color bindings automatically, it creates WinRT properties for each distinct color in the Lottie. The names of these properties were using the descriptive color names which are great for trying to understand code, but they're unnecessarily complex for property names. For example, naming a property Color_AlmostTurquoise_FF123456 is including information about the color that the user doesn't care about. The user simply wants to identify which property is which. So now we just name the properties "Color_XXXXXX" where XXXXXX is a 6 digit hex representation of the color, ignoring alpha. We continue to use descriptive names for methods and fields, as those are useful during debugging to understand the relationship between an element and what is showing on the screen. …

Use clearer names for automatically generated color bindings.

---

source/UIDataCodeGen/CodeGen/CppInstantiatorGeneratorBase.cs

We were generating a return after each version check instead of checking all the versions before returning. As a result, we'd only run on the highest supported version.

Fix issue with C++ multi-version support.

---

source/LottieToWinComp/TrimmedAnimatable.cs

TrimmedAnimatable with IReadOnlyList instead of Sequence can end up with a null reference when checking the length. Fix that.
This fix is part of an earlier PR, but because that PR is stuck waiting for code review, I'm adding it as a separate PR to get folks unblocked.

Fix TrimmedAnimatable null reference exception. 

---

LottieGen/LottieFileProcessor.cs

This is in response to issue #320, where a user was concerned about LottieGen producing non-deterministic output from a build run on different machines.
With this change, we'll no longer include path information or information about where or when the tool was run, and the only thing special that TestMode will do is remove the tool version from the output.

Do not include paths or machine info in generated code.

---

source/UIDataCodeGen/CodeGen/CppInstantiatorGeneratorBase.cs
source/UIDataCodeGen/CodeGen/CppwinrtInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/CxInstantiatorGenerator.cs

Apparently something changed in the way XAML gets info about CX classes - it used to compile but now it won't compile unless the classes are public. Public classes publish their metadata, which is presumably how XAML is now getting info about the classes. This change makes the CX classes always public.

CX classes stopped compiling because it wasn't public. Make it public.

---

LottieGen/README.md

This should make things a little clearer, especially wrt using LottieGen.exe from a local build without dotnet.exe.

Got some feedback from someone using this README for the first time.

---

LottieViewer/LottieVisualDiagnosticsViewModel.cs
LottieViewer/MainPage.xaml
LottieViewer/Scrubber.xaml
LottieViewer/Scrubber.xaml.cs
source/LottieToWinComp/TrimmedAnimatable.cs

This is a rewrite of the Scrubber to support markers. It also is a much nicer implementation of the
scrubber that reuses more of the XAML Slider functionality, and reduces the amount of copied XAML from
the default Slider style (from generic.xaml).
As I was adding this change, it became apparent that the way the XAML slider draws its track would
not work well with markers at 0.0 or 1.0 because the track ends up extending before and after the
0.0 and 1.0 positions which would make the markers look like they were incorrectly placed. So now
we do all of the drawing (track, decrease rectangle, and thumb) using Composition.
We also now mimic the mouse-over behavior of Slider so that the control feels a little more engaging.
This required hooking Composition into the VisualStateManager, which …

Adding markers to the scrubber.

---

source/Issues/LT0011.md
source/Issues/LT0016.md
source/Issues/LT0037.md
source/LottieData/Animatable.cs
source/LottieData/LottieData.projitems
source/LottieData/LottieObjectType.cs
source/LottieData/RoundCorners.cs
source/LottieData/Serialization/LottieCompositionYamlSerializer.cs
source/LottieData/ShapeContentType.cs
source/LottieData/Tools/Stats.cs
source/LottieReader/Serialization/ShapeLayerContents.cs
source/LottieToWinComp/CompositeOpacity.cs
source/LottieToWinComp/CompositionObjectFactory.cs
source/LottieToWinComp/ExpressionFactory.cs
source/LottieToWinComp/LottieToWinComp.projitems
source/LottieToWinComp/LottieToWinCompTranslator.Rectangles.cs
source/LottieToWinComp/LottieToWinCompTranslator.cs
source/LottieToWinComp/RectangleOrRoundedRectangleGeometry.cs
source/LottieToWinComp/ShapeContext.cs
source/LottieToWinComp/TranslationIssues.cs
source/LottieToWinComp/TrimmedAnimatable.cs

We were not handling the distinction between RoundCorners.Radius and Rectangle.Roundness. This change does a much better job.
Note that it gets the Trimming wrong for RoundCorners - that will come in a later fix. I'm getting this in now because it has so much refactoring that it will be hard to focus on the trimming algorithm alongside this.
These are the After Effects rules for how RoundCorners.Radius and Rectangle.Roundness interact:
RoundCorners.Radius is ignored if Rectangle.Roundness != 0.
RoundCorners.Radius is able to produce an ellipse if the radius is large enough.
Rectangle.Roundness creates round corners with equal X and Y radii, so it can never create an ellipse.

Fix translation of rectangles with RoundCorners.

---

LottieGen/CommandLineOptions.cs
LottieGen/LottieFileProcessor.cs
LottieGen/Program.cs
source/UIDataCodeGen/CodeGen/CSharpInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/CodegenConfiguration.cs
source/UIDataCodeGen/CodeGen/CppInstantiatorGeneratorBase.cs
source/UIDataCodeGen/CodeGen/CppwinrtInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/CxInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/IAnimatedVisualSourceInfo.cs
source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs

This switch is intended to exist only until we fork LottieGen to be WinUI3 only. Until then it is a convenient way to have the code generator output code that needs little hand tweaking to work with WinUI3.

Add a WinUI3 mode to LottieGen.

---

source/Lottie/ContentFactory.cs
source/Lottie/DisposableAnimatedVisual.cs
source/Lottie/Loader.cs
source/Lottie/Lottie.projitems
source/Lottie/LottieVisualSource.cs
source/Lottie/Uris.cs

There was a request (#333) to be able to load Lottie files from memory. This change allows that by enabling any IInputStream to be used.
As part of this change, I found some cruft that I could clean up, and I pulled out the classes for the Loader and ContentFactory and did some other straightforward refactoring.

Allow JSON to be loaded from any stream, including memory

---

source/Issues/LP0002.md
source/LottieReader/Serialization/ParsingIssues.cs

LP0002 is always populated from an exception message, which are supposed to have periods on the end. So most of the time we were getting double periods, which looks bad.

Prevent double periods in LP0002 error message.

---

source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs
source/UIDataCodeGen/CodeGen/Tables/GraphStatsMonospaceTableFormatter.cs
source/UIDataCodeGen/CodeGen/Tables/MonospaceTableFormatter.cs
source/WinCompData/CompositionAnimation.cs

We were showing the number of animation objects previously, but that doesn't really tell you how expensive animations are in DWM because the one animation might be started multiple times. Animator counts are a better representation of cost.
Here's an example of the extra info. Note the animators, and parameters counts.
```// ___________________________________________________________
// |       Object stats       | UAP v12 count | UAP v8 count |
// |__________________________|_______________|______________|
// | All CompositionObjects   |           567 |          567 |
// |--------------------------+---------------+--------------|
// | Expression animators     |            51 |           51 |
// | KeyFrame animators       |            50 |           50 |
// | Reference parameters     | …
```

Show animator counts in the object status table in generated code.

---

source/UIDataCodeGen/CodeGen/CSharpInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/CppInstantiatorGeneratorBase.cs

See #340 
This only affects Lotties with non-embedded images. When IsAnimatedVisualSourceDynamic is true the load of the Lottie is not considered complete until all the images have loaded. This guarantees that you never see a Lottie that is missing its images.
When IsAnimatedVisualSourceDynamic is false, the Lottie will load synchronously and the image will pop in when they are finally loaded.
Lotties with non-embedded images are quite rare, and one dev that tried to use them found them to be difficult because they had to wait for the Lottie to be loaded before playing. But they really didn't care about the images taking too long (they were on disk so they should show up really quickly). If we had made IsAnimatedVisualSourceDynamic default to false they wouldn't have had to deal with …

Change the default for IsAnimatedVisualSourceDynamic.

---

source/UIDataCodeGen/CodeGen/Cppwinrt/CppwinrtInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/Cx/CxInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs

Has some issues if the images are not found, but it works otherwise.
Includes some untested cleaning up of the CX code.

Get image layer working with cppwinrt.

---

source/LottieToWinComp/Paths.cs
source/UIDataCodeGen/CodeGen/Cppwinrt/CppwinrtInstantiatorGenerator.cs

The path translation optimizer didn't handle the case of paths that consist of single beziers. As a result, some animations were being incorrectly optimized into offset animations.
CppWinrt codegen was instantiating the implementation of CompositeEffect on the stack when it should have been on the heap.

Fix 2 bugs - path translation optimizer, cppwinrt codegen.

---

source/UIData/Tools/GraphCompactor.cs

An optimization stage was not taking into account the centerpoint property when moving properties up the tree. This was seen as a precomp that ended up offset from where it should have been.

Fix rendering issue caused by hole in the optimizer.

---

source/UIData/Tools/GraphCompactor.cs

We use CompositionVisualSurface to implement masks. CompositionVisualSurface allows a Visual tree to be used as a brush, however it ignores many of the properties on the root of the Visual tree it hosts.
The GraphCompactor attempts to push IsVisible animations higher up the tree, however before this fix it could push IsVisible into a Visual that was the root of a CompositionVisualSurface's tree, with the result that the IsVisible property would get ignored.
The fix disallows pushing of IsVisible into a Visual that is at the root of a CompositionVisualSurface's tree.

Fixes a hole in the GraphCompactor optimizer wrt visiblity and masks.

---

azure-pipelines.yml

We'd previously had to stick to 3.1.302 due to build issues.

Go back to using latest .NET 3.1 SDK.

---

Lottie-Windows.sln
Lottie-Windows/Lottie-Windows.csproj
LottieViewer/LottieViewer.csproj
LottieViewer/MainPage.xaml.cs
dlls/DotLottie/DotLottie.dll.csproj
source/DotLottie/DotLottie.projitems
source/DotLottie/DotLottie.shproj
source/DotLottie/DotLottieFile.cs
source/DotLottie/DotLottieFileAnimation.cs
source/DotLottie/InvalidLottieFileException.cs
source/Lottie/AnimatedVisualFactory.cs
source/Lottie/DotLottieLoader.cs
source/Lottie/ImageAssetHandler.cs
source/Lottie/InputStreamLoader.cs
source/Lottie/Instantiator.cs
source/Lottie/Loader.cs
source/Lottie/Lottie.projitems
source/Lottie/LottieVisualSource.cs
source/Lottie/StorageFileLoader.cs
source/Lottie/UriLoader.cs
source/LottieToWinComp/Images.cs
source/WinCompData/MetaData/UapVersionAttribute.cs

External images (i.e. images that are not embedded in the .JSON file) are a problem for LottieVisualSource because it doesn't know how to get them. For securit reasons, we don't want LottieVisualSource to have the ability to read files that are referenced from a Lottie .json file, and in many cases LottieVisualSource wouldn't be able to resolve the file because it doesn't have permissions.
This change adds an ImageAssetDelegate that the user can set on the AnimatedVisualSource in order to handle reading of external images.
This change also adds support for the .lottie format (see https://dotlottie.io). There is a parser for .lottie files, and support in LottieViewer for displaying Lotties from a .lottie file. Because .lottie files package images together with the .json Lottie file, it …

Allow external images to be loaded, and add .lottie file support

---

LottieViewer/MainPage.xaml
LottieViewer/MainPage.xaml.cs

Because Lotties can render differently on different UAP versions, it's important that users know what version of UAP they're using. That way, when they say "this doesn't look right", and I say "looks fine to me", we can check the UAP version easily to determine whether that accounts for the difference.

Show the current UAP version in Lottie Viewer.

---

Lottie-Windows.sln
source/LottieToWinComp/PathGeometryGroup.cs
source/LottieToWinComp/Paths.cs

As a result of looking again at the algorithm that we use to combine animated paths I decided it needed a lot more documentation and to be rewritten to make sure that we handle all cases.

Fix crash on some cases of path groups.

---

version.json

This reverts commit e881080e07bda951b6a197e8420bcd24509d2bed.
Jumped the gun on 7.1. We are staying on 7.0 for now.

Revert "Start version 7.1. (#388)"

---

LottieGen/LottieJsonFileProcessor.cs
source/Issues/LV0004.md
source/LottieData/LottieCompositionValidator.cs
source/LottieData/ValidationIssues.cs
source/UIDataCodeGen/Serialization/CompositionObjectDgmlSerializer.cs

Marker names don't have to be unique, but it's usually a bug if they are, so issue a warning if non-unique markers are found.
LottieGen didn't have validation turned on for some reason - now it does.
Small tweak in the DGML output: give LayerVisual its own category. This allows it to be displayed with a unique color.

Validate marker names.

---

source/Lottie/Instantiator.cs
source/UIData/Tools/ObjectGraph.cs
source/UIData/Tools/Optimizer.cs
source/UIDataCodeGen/CodeGen/CSharp/CSharpInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/Cppwinrt/CppwinrtInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/Cx/CxInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs
source/WinCompData/Mgce/GaussianBlurEffect.cs
source/WinCompData/WinCompData.projitems

This adds the effect and the code to instantiate and codegen it, but the translator does not yet use it.

Add GuassianBlurEffect to WinCompData.

---

source/LottieToWinComp/Brushes.cs
source/LottieToWinComp/ConvertTo.cs
source/LottieToWinComp/Masks.cs
source/LottieToWinComp/Transforms.cs
source/UIData/Tools/PropertyValueOptimizer.cs
source/UIDataCodeGen/CodeGen/Cx/CxInstantiatorGenerator.cs

The checking for default values should all be in the PropertyValueOptimizer.
Also, fix some bugs in the CX output.

Eliminate the default value checks from ConvertTo class.

---

source/UIDataCodeGen/Serialization/CompositionObjectDgmlSerializer.cs

Animated gradient brushes are expensive to render. This change allows us to see the gradient brushes in the DGML graph representation, and colors the animated ones in a very obvious red color.

Show gradient brushes in DGML.

---

source/Animatables/Animatable.cs
source/Animatables/AnimatableVector2.cs
source/Animatables/AnimatableVector3.cs

Also rationalized the select methods a bit to make them simpler.

Fix bug in the Select method for non-animatable animatables.

---

.gitignore
build/tools/packages.config

An update to Cake broke the build. For now, pin the version.

Pin a version of Cake to work around Cake change that broke the build

---

source/LottieMetadata/Duration.cs
source/LottieMetadata/Marker.cs
source/UIData/Tools/GraphCompactor.cs
source/UIData/Tools/VisibilityAtProgress.cs
source/UIData/Tools/VisibilityDescription.cs
source/UIData/UIData.projitems
source/UIDataCodeGen/CodeGen/MarkerInfo.cs
source/UIDataCodeGen/CodeGen/Tables/LottieMarkersMonospaceTableFormatter.cs

2 fixes for issues that became apparent as we started using markers more for AnimatedIcon.
1. Marker values refer to the start of a frame of interest. Due to floating point imprecision we could end up with a marker that refers to a progress value that is effectively just before the frame of interest. This can result in showing content from a previous frame.
This change attempts to fix it by nudging the marker progress values by 1/100th of a frame. This should guarantee that the marker is pointing to a time slightly after the start of the frame, even after the error caused by floating point imprecision.
2. There was a bug in the visibility optimizer that would cause some parts of the animation to remain visible when they should no longer be.

Fixes for AnimatedIcon

---

source/UIDataCodeGen/CodeGen/CSharp/CSharpInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs
source/UIDataCodeGen/CodeGen/SourceMetadata.cs

This makes it much easier to figure out what is causing issues in animations.
Also remove the "readonly" on properties in the generated C# because they aren't supported by the language versions used in UWP.

Show frame numbers in generated code.

---

source/WinCompData/Expressions/Boolean.cs
source/WinCompData/Expressions/Color.cs
source/WinCompData/Expressions/Expression.cs
source/WinCompData/Expressions/Matrix3x2.cs
source/WinCompData/Expressions/Precedence.cs
source/WinCompData/Expressions/Scalar.cs
source/WinCompData/Expressions/Vector2.cs
source/WinCompData/Expressions/Vector3.cs
source/WinCompData/Expressions/Vector4.cs
source/WinCompData/WinCompData.projitems
tests/LottieGenCorpus.ps1

The logic for determining whether an expression could be simplified was sometimes wrong because it ended up hitting an overridden equality operator which compared the already-simplified values.
Also fixed the test script to look at last write time when determining which is the latest build of LottieGen.exe to run. We were looking at creation time, but it turns out that when the compiler builds, it doesn't cause the creation time to be updated if the output file previously existed. Our test script could accidentally use a release build when the latest build was actually a debug build, resulting in the test running on an old build.

Fix some missing simplifications in Composition expressions.

---

Lottie-Windows/Lottie-Windows.csproj
LottieGen/MSBuildTask/LottieGen.MsBuild.csproj
LottieViewer/LottieViewer.csproj
dlls/GenericData/GenericData.dll.csproj
dlls/LottieData/LottieData.dll.csproj
dlls/LottieMetadata/LottieMetadata.dll.csproj
dlls/LottieReader/LottieReader.dll.csproj
samples/LottieSamples/LottieSamples.csproj
version.json

Error reported:
Microsoft.Toolkit.Uwp.UI.Lottie v7 uses System.Text.Encodings.Web v4.7.1 which has a high severity security vulnerability and as such doesn't pass component governance
This upgrades all of the runtime NuGet packages to the latest version.

Fix for security issue in System.Text.Encodings.Web v4.7.1.

---

Lottie-Windows/Lottie-Windows.csproj

Certain versions of System.Text.Encodings.Web are flagged as having possible security vulnerabilities. Version 5.0.1 is the newest version that is marked as safe.

Update Lottie to use 5.0.1 of System.Text.Encodings.Web

---

LottieGen/MSBuildTask/LottieGen.MsBuild.props
LottieGen/MSBuildTask/LottieGen.cs

- Parameter validation no longer fails on valid params
- Fixed props file path to LottieGen dll (#443)
- Fixed path generation for LottieGen exe
- Converted parameter types which are not supported by MSBuild to acceptable types
- Added escaping to command-line args to avoid mangling file paths

Fixes for MSBuild task

---

source/LottieToWinComp/Brushes.cs
source/LottieToWinComp/ExpressionFactory.cs
source/LottieToWinComp/Rectangles.cs
source/LottieToWinComp/ShapeLayerContext.cs
source/LottieToWinComp/Shapes.cs
source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs

Because of the difference in how gradient fill for rectangles works in **WinComp API** and Lottie, previously it was displayed incorrectly.
**WinComp API** uses top left corner of rectangle as point [0, 0] while Lottie uses middle-middle instead. To account for this difference we need to add **(Rectangle.Size/2)** to Start and End points of gradients. We can't add a constant value since **Rectangle.Size** can also be animated, and if it is animated, we need to use expression animation.
In this change, I added InternalOffset class for rectangle shapes, which propagates information about offset to the gradients and then this offset is applied to Start and End points.
Examples below show how it works now:

Gradient fill for rectangle(rounded rectangle) shape fixed

---

source/Animatables/Vector2.cs
source/LottieToWinComp/Paths.cs

Implemented After Effects algorithm for **"Round Corners"** effect. (There is a comment in Shapes.cs:634 that mentioned this _// TODO - can round corners be implemented by composing cubic Beziers?_)
For now I added support only for one-path + no-animations scenario, in following PR will also add support for multiple paths and animated path/radius. Just to keep this PR small.
.
.
.
To make a round corner we are stepping `radius` pixels in both directions from the corner, and joining resulting points together with a bezier curve (`MakeCubicBezier` takes 3 points and creates a bezier curve). But also there is a tricky case, when one end of the segment is already curved, this case described on picture 2.
Algorithm loops over segments and creates new array of segments, there are several cases …

Add support for round corners if there is no animations

---

Lottie-Windows.sln
LottieGen/LottieGen.sln
source/Issues/LT0016.md
source/Issues/LT0043.md
source/LottieToWinComp/Paths.cs
source/LottieToWinComp/Shapes.cs
source/LottieToWinComp/TranslationIssues.cs

In previous PR I added basic support for AE's "Round Corner" modifier but without animations. In this PR I added approximation* of animated version of this modifier. 
*We can not animate it 100% perfect as in After Effects, because in after effects they are applying this modifier to the path after interpolation happened, but in our case we can't do that since Composition layer do not support this modifier directly, so instead we are applying this modifier to each keyframe and then Composition interpolates between these kayframes. But in most cases, it looks indistinguishable from After Effects.
- Radius animated:
- Path animated:

Added support for animated round corners modifier

---

source/Lottie/Instantiator.cs
source/LottieToWinComp/Animate.cs
source/LottieToWinComp/CompositionObjectFactory.cs
source/LottieToWinComp/PreComps.cs
source/UIData/Tools/GraphCompactor.cs
source/UIData/Tools/ObjectGraph.cs
source/UIData/Tools/Optimizer.cs
source/UIData/Tools/Stats.cs
source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs
source/WinCompData/CompositionMaskBrush.cs
source/WinCompData/CompositionObjectType.cs
source/WinCompData/Compositor.cs
source/WinCompData/WinCompData.projitems

Blur effect rewritten to use SurfaceBrush. Now there is no more visual glitches.
Also added CompositionMaskBrush since we need it to apply shadow color to the Visual node.

Enabled blur effect for PreComp layers

---

source/LottieToWinComp/Shapes.cs

Previously if shape layer had animated or non-100% opacity it generated color expression animation (`"ColorRGB(my.Opacity, r, g, b)"`). Instead of that we can create separate visual with one child - this shape layer, and then animate opacity of the visual. We already have this logic for masks and effects so I just added another condition.

Translate shape as a separate visual with child if it has animated opacity

---

source/Lottie/Loader.cs
source/LottieData/Optimization/Experimental/MergeHelper.cs
source/LottieReader/Serialization/LottieCompositionReader.cs

- I added more merge helper methods (They are used in some animations). 
- Removed some checks since it seems that they are no longer needed. Now we can optimize more cases.
- We should be able to merge nested LayerPreComp (Previously I noticed a bug with that so I added this check but I can no longer reproduce it). 
- I don't know why I added `aAsset == bAsset` check since I'm making a copy of it anyway a line below (`WithTimeOffset` creates a copy).
- Turned out that previously I was calling optimizer in wrong place. It was too deep so LottieGen called it twice and even with command line option -DisableLottieMergeOptimizer. So I moved it higher in the stack.

Added more merge optimizer options and moved optimizer call for LottieViewer

---

LottieGen/MSBuildTask/LottieGen.cs
source/UIDataCodeGen/CodeGen/CSharp/CSharpInstantiatorGenerator.cs

- Replace `is null` usages in generated code with downlevel equivalent to support older versions of C# in client applications
- Fix MSBuild task to send bool args correctly. The LottieGen cmdline only allows flags to be set without an associated value arg.

Replace 'is null' with more compatible clause and fix MSBuild bug

---

source/UIData/Tools/GraphCompactor.cs

It seems that we should not coalesce root container visual with it's child. Sometimes users of Lottie are changing height/width/scale properties of the root visual and in combination with non-null ClipRect of child it may result in wrong clipping being applied.
This started appearing after new optimization was added because new optimization often merges together immediate children of the root node, so that GraphCompactor then tries to coalesce root node and it's new single child.

[LottieGen] Graph compactor fix. Do not coalesce root container visuals.

---

LottieViewer/LottieViewer.csproj
LottieViewer/MainPage.xaml
LottieViewer/MainPage.xaml.cs
LottieViewer/PixelViewElement.cs

Adding **PixelView** feature. This feature should allow designers to examine animations precisely pixel-by-pixel, so that they can ensure that animation will be displayed correctly at any resolution.

[LottieViewer] Pixel View feature added

---

source/LottieToWinComp/Effects.cs

We need this version check for DropShadow effect since it can't be supported for UAP <=7 , so just fall back to no shadow in this case.

[LottieGen] Fixed UAP version check for Drop Shadow effect

---

Lottie-Windows.sln
LottieGen/LottieGen.sln
source/Issues/LT0044.md
source/LottieToWinComp/Masks.cs
source/LottieToWinComp/TranslationIssues.cs

`translatedLayer.GetVisualRoot` may return `null` if it detects that layer will not be visible (it has opacity zero, or visible time range is out of parent's time range). If this layer should be matted or should be used as a matte layer it may cause some artifacts to appear.
New implementation should be more robust and should handle most corner cases.
1. If both `mattedLayer` and `matte` are not null -> compose them into one layer
2. If `mattedLayer` is `null` -> skip both layers
3. If `matte` layers is `null` -> we can skip them too, (!) except for the case when `MatteType` is `Invert`, in this case we are inverting invisible layer which mean that it is always visible, so we should keep `mattedLayer`

Fixed ComposeMatteLayers method to work for invisible layers

---

settings.xamlstyler

I was comparing your settings.xamlstyler with mine to see the difference and noticed a few typos (I've been using this file for about a month and copied the settings from here https://github.com/Xavalon/XamlStyler/wiki/External-Configurations).
I originally noticed this issue in
WindowsCommunityToolkit and thought it might be a CopyPaste issue

Fixed typos in settings.xamlstyler

---

source/LottieToWinComp/Shapes.cs

It seems that AfterEffects is applying layer combination mode in reverse order. It does not affect Intersect/Union/Xor but it affects how Exclude mode works, so we need to reverse the order. `Exclude[layer1, layer2]` should be interpreted as `(layer2 - layer1)`
Note: We should do more investigation how it works  for more than 3 layers, but currently I do not have an example of animation that uses 3 layers or more with Exclude mode, but even then it should be pretty rare case. `Exclude[layer1, layer2, layer3]` may be interpreted as `(layer3 - (layer2 - layer1))` or `((layer3 - layer2) - layer1)`.
Should fix #482

[LottieGen] Fixed layer combining for Exclude mode

---

source/LottieToWinComp/Transforms.cs
source/UIData/Tools/GraphCompactor.cs
source/UIDataCodeGen/CodeGen/CSharp/CSharpInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/CodegenConfiguration.cs
source/UIDataCodeGen/CodeGen/Cppwinrt/CppwinrtInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/Cx/CxInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/IAnimatedVisualInfo.cs
source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs

Added implementation of IAnimatedVisual2 interface that is going to be added to xaml controls: https://github.com/microsoft/microsoft-ui-xaml/pull/6268. It is disabled by a boolean flag for now, later we will decide if we want to enable it by default (with version check) or to add a command line argument.
```
interface IAnimatedVisual2 {
void InstantiateAnimations(); 
void DestroyAnimations();
}
```
We also have to ensure that all the animations have zero keyframes (progress = 0.0) in order to correctly re-instantiate animation states, previously we were discarding some zero keyframes.

[LottieGen] Added IAnimatedVisual2 implementation preview.

---

source/LottieToWinComp/Shapes.cs

Reverting the #459, it can result in wrong translation in some rare cases. Will need to investigate it more in the future.

ShapeLayerTranslator fix

---

source/LottieToWinComp/Effects.cs

Fixing translation of shadow effect. If source of the shadow is not visible it does not make shadow disappear, so here I'm pushing `IsVisible` property up so that this property controls visibility of both, source and shadow visuals.

Fixed visibility property for visuals with shadow

---

Lottie-Windows.sln
LottieGen/LottieGen.sln
source/Issues/LT0045.md
source/LottieToWinComp/Paths.cs
source/LottieToWinComp/TranslationIssues.cs

Some animations can't be played in Lottie-Windows because of WinComp Api limitation: number of segments in path animation should be the same for all keyframes, but After Effects supports animation with any number of segments.
Added a workaround to make number of segments equal for all the keyframes by adding 0-length segments to the path at the end. It may result in a little bit different animation from what you see in After Effects.
#493

[LottieGen] Added workaround to make path animations playable even with different number of segments in keyframes

---

source/LottieToWinComp/Brushes.cs
source/LottieToWinComp/ExpressionFactory.cs
source/LottieToWinComp/Rectangles.cs
source/WinCompData/Expressions/Vector2.cs

We've already have a fix for this, but turned out that it had some flaws: https://github.com/CommunityToolkit/Lottie-Windows/pull/450
- Current implementation of WinComp API behaves in a different way for Rounded Rectangle geometry and regular Rectangle Geometry. So I added an additional check for this. 
- Previous implementation didn't take into account position of the rectangle.
- Radial gradient behaves in a different way than linear gradient, so it doesn't need the offset at all.

Fixed gradient brush offset for rectangle geometry

---

source/Lottie/Instantiator.cs
source/LottieToWinComp/CompositionObjectFactory.cs
source/LottieToWinComp/Effects.cs
source/LottieToWinComp/Masks.cs
source/UIData/Tools/ObjectGraph.cs
source/UIData/Tools/Optimizer.cs
source/UIData/Tools/Stats.cs
source/UIDataCodeGen/CodeGen/CSharp/CSharpInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/Cppwinrt/CppwinrtInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/Cx/CxInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs
source/WinCompData/CompositionEffectBrush.cs
source/WinCompData/CompositionEffectFactory.cs
source/WinCompData/CompositionEffectSourceParameter.cs
source/WinCompData/Mgce/CompositeEffect.cs
source/WinCompData/Mgce/GaussianBlurEffect.cs
source/WinCompData/Mgce/GraphicsEffectBase.cs

Lottie-Windows was previously generating one factory per each effect. I refactored the code a little bit so that we can reference same factory for multiple EffectBrushes which will reduce number of factories being created. OS does in fact have it's own cache for effects, so this change does not increase performance, just decreases generated code size.
Also small fix: fixed blur + shadow radius scaling, After Effects blur of radius `R` corresponds to Windows blur of radius `R / 3.33`

[LottieGen] Refactored effects, added cache for factories

---

source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs

Previous code was generating "var.Properties" code instead of "var.Properties()" for cppwinrt

Fixed properties call codegen

---

source/UIDataCodeGen/CodeGen/CSharp/CSharpInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/CodeBuilder.cs

This change should reduce size of embeded images that are exported as bytes arrays currently by a factor of 3, by exporting them as base64. For c#  only for now, because it is unclear which base64 API to use for winrt and cxx

Use base64 string instead of array of bytes for CSharp code gen.

---

source/UIDataCodeGen/CodeGen/CSharp/CSharpInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/CodegenConfiguration.cs
source/UIDataCodeGen/CodeGen/Cppwinrt/CppwinrtInstantiatorGenerator.cs

There were some problems with generating code for WinUI3, a lot of namespaces were wrong (Microsoft vs Windows) and also some types are not available for WinUI3. Fixed so that LottieGen now work correctly for WinUI3 as well.

Fixed codegen to produce correct WinUI3 code

---

source/UIDataCodeGen/CodeGen/CodegenConfiguration.cs
source/UIDataCodeGen/CodeGen/Cppwinrt/CppwinrtInstantiatorGenerator.cs
source/UIDataCodeGen/CodeGen/IAnimatedVisualInfo.cs

For CppWinRT we should declare all the interfaces that we want to implement. Previously we declared IAnimatedVisual2 without IAnimatedVisual which caused animations to not show up.
Also changed min version of WinUI from 2.7 to 2.8 for IAnimatedVisual2 because it became finally available only in 2.8.

Fixed IAnimatedVisual impl line for WinUI 2.8 (+fixed 2.7 -> 2.8)

---

source/UIDataCodeGen/CodeGen/CSharp/CSharpInstantiatorGenerator.cs

According to source\UIDataCodeGen\CodeGen\CSharp\CSharpInstantiatorGenerator.cs line 376
```c#
// Add fields for each of the theme properties.
// Not needed if generating a DependencyObject - the values will be stored in DependencyPropertys.
if (!SourceInfo.GenerateDependencyObject)
{
foreach (var prop in SourceInfo.SourceMetadata.PropertyBindings)
{
var defaultValue = GetDefaultPropertyBindingValue(prop);
WriteInitializedField(builder, ExposedType(prop), $"_theme{prop.BindingName}", _s.VariableInitialization($"c_theme{prop.BindingName}"));
}
}
```
If used GenerateDependencyObject parameter there is no variable call "_theme{prop.BindingName}", when write the SetColorProperty function, it should change the variable name

Fix wrong variable name with GenerateDependencyObject parameter

---

source/Lottie/Loader.cs
source/LottieData/Optimization/LayersGraph.cs

It looks like the recursive graph walk in LayersGraph.cs was intended to use the visited set of nodes as part of its traversal. In a quick test, I saw a Lottie json file load time go from 2 minutes down to 15 seconds.
Discovered by running the Visual Studio profiler over the Lottie Viewer

Update IsChildOf graph walk in LayersGraph.cs

---

Lottie-Windows.sln
Lottie-Windows/Lottie-Windows-UwpNET/Lottie-Windows-UwpNET.csproj
azure-pipelines.yml
source/Lottie/LottieVisualSource.cs
source/UIData/Tools/Canonicalizer.cs
source/UIData/Tools/GraphCompactor.cs
source/UIData/Tools/PropertyValueOptimizer.cs
source/UIData/Tools/Stats.cs
source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs
source/UIDataCodeGen/CodeGen/NodeNamer.cs
source/UIDataCodeGen/CodeGen/Tables/GraphStatsMonospaceTableFormatter.cs
source/WinCompData/CompositionObject.cs
source/WinCompData/Mgcg/CanvasPathBuilder.cs

Lottie-Windows-UwpNET.csproj targets .NET9 and system XAML + WinUI2. It will be bundled together with Lottie-Windows-UWP into the same nuget package.
Some code changes have been made to support this new project, namely:
1. Convert the generic List to non-generic ArrayList in CompositionObject.cs and CanvasPathBuilder.cs.
2. Convert CompositionObject's "Animators" property from IReadOnlyList to IEnumerable.
3. New build constant "UWPNET" used in LottieVisualSource.cs, defined by Lottie-Windows-UwpNET.csproj.

Add Lottie-Windows-UwpNET.csproj

---

Lottie-Windows/Lottie-Windows-Uwp/Lottie-Windows-Uwp.csproj
Lottie-Windows/Lottie-Windows-UwpNET/Lottie-Windows-UwpNET.csproj
Lottie-Windows/Lottie-Windows-WinUI3/Lottie-Windows-WinUI3.csproj
Lottie-Windows/Lottie-Windows.props

If a consumer wants to use both UWPNET and WinUI3, the DLL names conflict since they're both "CommunityToolkit.WinUI.Lottie.dll". So rename the UWPNET one to CommunityToolkit.**Uwp**.Lottie.dll.
```<CsWinRTComponent>true</CsWinRTComponent>``` prevents the renaming, and it's not required for C# consumers so drop this as well.

Switch UWPNET assembly name to CommunityToolkit.Uwp.Lottie

---

Lottie-Windows/Lottie-Windows-WinUI3/Lottie-Windows-WinUI3.csproj

The WinUI3 nuget's .pri file references WebView2Loader.dll which causes WebView2Loader.dll to be included into the appx package payload and breaks the build on consumer's end. 
This is due to an old bug in the WV2 nuget, which happens to exist in the version that WinAppSDK pulls in. So adding an explicit dependency to WV2 with a newer version fixes this issue.
Verified by building & generating nupkg and inspecting the .pri file produced - no more WebView2Loader.dll!

Add WV2 reference in WinUI3 project
