.github/CODEOWNERS
This will help GitHub assign reviewers for PRs.
=> Add a CODEOWNERS file.

dlls/README.md
Seeing as this came up as an Issue question previously, make sure it's answered in the source.
=> Add a README for the dlls directory.

source/WinCompData/CodeGen/NodeNamer.cs
This makes the generated code easier to read, as the purpose of the animation is in the name.
=> Prepend the target property name to the name of an animation.

Directory.Build.props, LottieGen/Glob.cs, Toolkit.ruleset, source/Lottie/Instantiator.cs, source/Lottie/LottieVisualSource.cs, source/LottieData/Animatable.cs, source/LottieData/AssetCollection.cs, source/LottieData/GradientStop.cs, source/LottieData/HoldEasing.cs, source/LottieData/LayerCollection.cs, source/LottieData/LinearEasing.cs, source/LottieData/LottieCompositionValidator.cs, source/LottieReader/Serialization/LottieCompositionReader.cs, source/LottieToWinComp/LottieToWinCompTranslator.cs, source/WinCompData/CodeGen/CSharpInstantiatorGenerator.cs, source/WinCompData/CodeGen/CxInstantiatorGenerator.cs, source/WinCompData/CodeGen/InstantiatorGeneratorBase.cs, source/WinCompData/CodeGen/NodeNamer.cs, source/WinCompData/Expressions/CubicBezierFunction2.cs, source/WinCompData/Expressions/Expression.cs, source/WinCompData/Expressions/TypeAssert.cs, source/WinCompData/Tools/ApiCompatibility.cs, source/WinCompData/Tools/Graph.cs, source/WinCompData/Tools/ObjectGraph.cs, source/WinCompData/Wui/Color.cs
Enable more warnings and fix ones that were easy.
=> Turn on warnings as errors.

source/LottieReader/Serialization/LottieCompositionReader.cs
Harden the LottieCompositionReader against layers that have no index. And support new Bodymovin schema.
=> Support for new Bodymovin schema. Reader hardening.

source/LottieData/ImageLayer.cs, source/LottieData/Layer.cs, source/LottieData/NullLayer.cs, source/LottieData/PreCompLayer.cs, source/LottieData/ShapeLayer.cs, source/LottieData/SolidLayer.cs, source/LottieData/TextLayer.cs, source/LottieReader/Serialization/LottieCompositionReader.cs
=> Encapsulate the arguments to the Layer constructor. 

VERSION_HISTORY.md
=> Update version history for 5.1.1

source/LottieToWinComp/LottieToWinCompTranslator.cs
Simplifies the code a bit.
This change was done previously but got lost somewhere.
=> Small refactoring to simplify and share code for creating shape visual

LottieGen/Program.cs, source/LottieData/AssetCollection.cs, source/LottieData/Optimization/Optimizer.cs, source/LottieReader/Serialization/LottieCompositionReader.cs
Deal with colors that have objects in the alpha channel.
Deal with key frame that are redundant (they have a following keyframe at the same frame offset).
Deal with assets that have non-unique IDs.
Report unexpected exceptions in LottieGen.
=> Harden against some unexpected cases in Lottie json files.

LottieGen/LottieFileProcessor.cs, source/Lottie/Instantiator.cs, source/LottieToWinComp/CompositionObjectFactory.cs, source/UIData/CodeGen/Canonicalizer.cs, source/UIData/CodeGen/CppStringifier.cs, source/UIData/CodeGen/InstantiatorGeneratorBase.cs, source/UIData/CodeGen/NodeNamer.cs, source/UIData/CodeGen/Optimizer.cs, source/UIData/CodeGen/Stringifier.cs, source/UIData/Serialization/CompositionObjectDgmlSerializer.cs, source/UIData/Tools/ObjectGraph.cs, source/UIData/Tools/Stats.cs, source/WinCompData/CompositionObjectType.cs, source/WinCompData/Compositor.cs, source/WinCompData/Serialization/CompositionObjectXmlSerializer.cs, source/WinCompData/Vector4KeyFrameAnimation.cs, source/WinCompData/WinCompData.projitems
This is a prerequisite for supporting opacity and color animated at the same time on the same object.
=> Add support for WUC Vector4KeyFrameAnimation.

source/Lottie/Instantiator.cs, source/LottieToWinComp/CompositionObjectFactory.cs, source/LottieToWinComp/ExpressionFactory.cs, source/LottieToWinComp/LottieToWinCompTranslator.cs, source/UIData/Tools/Canonicalizer.cs, source/UIData/Tools/Optimizer.cs, source/UIData/Tools/TreeReducer.cs, source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs, source/UIDataCodeGen/CodeGen/NodeNamer.cs, source/WinCompData/CompositionColorBrush.cs, source/WinCompData/Compositor.cs, source/WinCompData/Expressions/Expression.cs, source/WinCompData/Serialization/CompositionObjectXmlSerializer.cs
Support ColorBrushes that don't have their Color property set.
Support Color expressions in the ExpressionAnimation language helpers.
Support ColorBrushes animated by ExpresssionAnimations.
=> CompositionColorBrush enhancements.

source/UIDataCodeGen/CodeGen/CSharpInstantiatorGenerator.cs, source/UIDataCodeGen/CodeGen/CxInstantiatorGenerator.cs
We were emitting the source info only for IAnimatedVisualSource. It should have been on IDynamicAnimatedVisualSource too.
=> Emit source info on IDynamicAnimatedVisualSource

source/LottieData/ImageLayer.cs, source/LottieData/NullLayer.cs, source/LottieData/PreCompLayer.cs, source/LottieData/SolidLayer.cs, source/LottieToWinComp/CubicBezierFunction2.cs, source/LottieToWinComp/LottieToMultiVersionWinCompTranslator.cs, source/LottieToWinComp/PropertyBindingsParser.cs, source/LottieToWinComp/TranslationContext.cs, source/UIData/Tools/TreeReducer.cs, source/UIDataCodeGen/CodeGen/CodeBuilder.cs, source/UIDataCodeGen/CodeGen/CxInstantiatorGenerator.cs, source/WinCompData/CubicBezierEasingFunction.cs, source/WinCompData/Expressions/ExpressionType.cs, source/WinCompData/KeyFrameAnimation_.cs
These changes do not affect the output in any way. They are mostly
things discovered by the VS automatic code cleanup, or debugging
helpers.
=> Code cleanup.

source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs
The root progress animation expression ("_.Progress") is used to synchronize (almost) all of the animations in a Lottie. It is handy to be able to recognize it in the code.
=> For readability of the generated code, special name for root progress animation

LottieGen/LottieGen.csproj
This information is displayed by NuGet.
=> Update description, and add tags for LottieGen.

source/UIData/Tools/Graph.cs, source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs
This simplifies the codegen for the creation of some objects. This results in smaller
outputs and a slight perf improvement.
=> Simplified factories for some common cases.

source/UIData/Tools/GraphCompactor.cs
An obvious error in the GraphCompactor could result in visibility staying on for too long.
=> Fixes an issue with a visibility optimization.

source/GenericData/GenericDataList.cs, source/GenericData/GenericDataMap.cs, source/LottieToWinComp/LottieToWinCompTranslator.cs, source/WinCompData/Expressions/Expression_.cs
I didn't know this was possible before. It's neater so let's use it consistenly.
=> Use null-coalescing compound assignment for caches.

azure-pipelines.yml
Necessary to start consuming cswinrt.
=> Update the version of nuget.

source/LottieToWinComp/LottieToWinCompTranslator.cs
This way of translating paths applies rarely, but when it does it solves a couple problems:
1) It enables some animated paths to be rendered on UAP versions < 12.
2) It is more efficient than animating a path.
=> Convert animated paths to static paths with animated offset if possible

samples/LottieSamples/Scenarios/AsyncPage.xaml, samples/LottieSamples/Scenarios/CodegenPage.xaml, samples/LottieSamples/Scenarios/FallbackPage.xaml, samples/LottieSamples/Scenarios/JsonPage.xaml, samples/LottieSamples/Scenarios/ModifyPage.xaml, samples/LottieSamples/Scenarios/PlaybackPage.xaml, samples/LottieSamples/Scenarios/ProgressPage.xaml, samples/LottieSamples/Scenarios/SegmentPage.xaml
Add necessary UIA names and labels and remove items from UIA tree that are not helpful.
Closes #52
=> Improve accessibility of sample app

source/LottieData/Animatable.cs, source/LottieData/ExtensionMethods.cs, source/LottieData/Layer.cs, source/LottieData/Optimization/Optimizer.cs, source/LottieData/Serialization/LottieCompositionYamlSerializer.cs, source/LottieData/ShapeGroup.cs, source/LottieData/ShapeLayer.cs, source/LottieData/SolidColorStroke.cs, source/LottieData/Tools/Stats.cs, source/LottieToWinComp/AnimatableVector3Rewriter.cs, source/LottieToWinComp/CompositeOpacity.cs, source/LottieToWinComp/LottieToWinCompTranslator.cs, source/LottieToWinComp/TranslationContext.cs, source/LottieToWinComp/TrimmedAnimatable.cs
IReadOnlyList is more convenient, and ReadOnlySpan wasn't buying us anything except slicing because it was only being used to wrap arrays.
=> Replace ReadOnlySpan with IReadOnlyList.

LottieGen/LottieFileProcessor.cs, LottieGen/Program.cs
In response to a CR of another change.
=> Improve naming of the _lottieFilePath field in LottieFileProcessor.

source/LottieData/Animatable.cs, source/LottieToWinComp/CompositeOpacity.cs, source/LottieToWinComp/LottieToWinCompTranslator.Rectangles.cs, source/LottieToWinComp/LottieToWinCompTranslator.cs, source/LottieToWinComp/ShapeContext.cs, source/LottieToWinComp/TrimmedAnimatable.cs
This was suggested in a previous PR. Actually doing it now.
=> Renaming of some methods that return booleans for clarity.

source/UIDataCodeGen/CodeGen/Cx/CxInstantiatorGenerator.cs, source/UIDataCodeGen/CodeGen/Cx/CxStringifier.cs
Fixes needed after first tests on CX since adding the markers and property support.
=> Fix codegen errors.

source/LottieData/Opacity.cs, source/LottieReader/Serialization/Animatables.cs, source/LottieReader/Serialization/Effects.cs, source/LottieReader/Serialization/LottieCompositionReader.cs, source/LottieToWinComp/CompositionObjectFactory.cs, source/LottieToWinComp/ConvertTo.cs, source/LottieToWinComp/PreComps.cs
This is currently turned off, however we do everything except adding the shadow to the LayerVisual so that the code is being exercised.
I have not output any issues yet for the cases we don't handle because we don't know how long before LayerVisual is fixed, and the set of issues might need changing when LayerVisual is finally working.
=> Implement DropShadow effect.

source/Issues/LP0008.md, source/LottieData/BlurDimension.cs, source/LottieData/Effect.cs, source/LottieData/Enum.cs, source/LottieData/GaussianBlurEffect.cs, source/LottieData/LottieData.projitems, source/LottieData/Serialization/LottieCompositionYamlSerializer.cs, source/LottieReader/Serialization/Animatables.cs, source/LottieReader/Serialization/Effects.cs, source/LottieReader/Serialization/ParsingIssues.cs
Blur is not yet supported in the translator.
=> Parse After Effects blur effects from Lottie files.

source/LottieData/GaussianBlurEffect.cs, source/LottieData/Serialization/LottieCompositionYamlSerializer.cs, source/LottieReader/Serialization/Effects.cs, source/YamlData/YamlFactory.cs, source/YamlData/YamlScalar.cs
And polish the yaml serializer a bit.
=> Support a Gaussian blur effect field that sometimes shows up.

LottieViewer/Scrubber.xaml.cs
Previously, you'd press the arrow keys 10 times before the tooltip value would change. That was confusing! Now the tooltip will always change in response to the arrow keys.
=> Show another decimal place on the LottieViewer tooltip.

version.json
Updating the version file before we create the update release branch for 7.0.2
=> Update version to 7.0.2

source/UIDataCodeGen/CodeGen/InstantiatorGeneratorBase.cs
Fixed an issue that causes build system to fail. Seems that nullable type checks became more strict
=> Fixed mismatch of nullable types

version.json
Spinning a new patch release to publish the recent fixes for for MSbuild
=> Update version to 7.0.3

source/LottieData/Optimization/Experimental/MergeHelper.cs
Added merge optimization for SolidColorStroke. It is needed to optimize some animations that use strokes
=> Added SolidColorStroke merge optimization

version.json
Updated version file to publish new nuget.
=> Updated version file

source/Lottie/Loader.cs, source/LottieData/Optimization/Experimental/MergeHelper.cs, source/LottieReader/Serialization/LottieCompositionReader.cs
We haven't released 7.0.4 yet so I'm merging recent fixes and changes to rel/7.0.4
=> Merge master to rel/7.0.4

version.json
We released 7.0.5 and didn't change the version int master branch. Fixing it.
=> [Version] Version changed to 7.0.5

README.md, samples/LottieSamples/Scenarios/AsyncPage.xaml, samples/LottieSamples/Scenarios/CodegenPage.xaml, samples/LottieSamples/Scenarios/FallbackPage.xaml, samples/LottieSamples/Scenarios/JsonPage.xaml, samples/LottieSamples/Scenarios/ModifyPage.xaml, samples/LottieSamples/Scenarios/PlaybackPage.xaml, samples/LottieSamples/Scenarios/ProgressPage.xaml, samples/LottieSamples/Scenarios/SegmentPage.xaml, source/Lottie/Issue.cs, version.json
There were some places in the repo that were still referencing old branch. Fixed
=> Sync some files to the new branch name

source/LottieToWinComp/CubicBezierFunction2.cs
Previous implementation had too many corner cases, for instance it was not working proper with zero vectors. Replaced it with vector-based check. Also added an epsilon so that if we are getting bezier curve that is really close to a line, we will translate it to a line, since linear animation is much cheaper in runtime.
=> Fixed bezier curve IsLinear check

source/UIDataCodeGen/CodeGen/CSharp/CSharpInstantiatorGenerator.cs
=> Unify the code for cs codegen between IDynamicAVS and regular IAVS

Lottie-Windows-WinUI3-Controls/Lottie-Windows-WinUI3-Controls.csproj, Lottie-Windows/Lottie-Windows-WinUI3/Lottie-Windows-WinUI3.csproj, LottieIsland/AutomationBase.cpp, LottieIsland/AutomationBase.h, LottieIsland/AutomationCallbackHandler.h, LottieIsland/AutomationCallbackRevoker.h, LottieIsland/AutomationElement.cpp, LottieIsland/AutomationElement.h, LottieIsland/AutomationFragment.cpp, LottieIsland/AutomationFragment.h, LottieIsland/AutomationFragmentRoot.cpp, LottieIsland/AutomationFragmentRoot.h, LottieIsland/LottieContentIsland.cpp, LottieIsland/LottieContentIsland.h, LottieIsland/LottieIsland.vcxproj, LottieIsland/LottieIsland.vcxproj.filters, LottieIsland/LottieIslandAutomationProvider.cpp, LottieIsland/LottieIslandAutomationProvider.h, LottieIsland/packages.config, LottieIslandProjection/LottieIslandProjection.csproj, LottieWinRT/LottieWinRT.csproj, SimpleLottieIslandApp/SimpleLottieIslandApp.cpp, SimpleLottieIslandApp/SimpleLottieIslandApp.vcxproj, SimpleLottieIslandApp/packages.config
Adds an automation provider for a Lottie Island + automation infrastructure so that it can be easily extended in the future.
=> Add UIA support

README.md
Fixed the version of WinUI3 in the command. It needs to be `-WinUIVersion 3.0` instead of `-WinUIVersion 3`
<br>
=> Fixed the version of WinUI3 in the command
